### ISSUE TITLE
Sharkey Support

### ISSUE THREAD

**Issue by Rorschach1010** [DimensionDev/Flare#604]
First off, you created one of the most beautiful fedi apps and I really like the feature-set. I'm considering switching over from Moshidon. However, I am surprised to see, that it's not possible to login to Sharkey instances. Since flare supports mastodon as well as misskey, I would have guessed that this is kinda automatic. sharkey is a misskey fork after all and even implemented the mastodon API.

Since I use my sharkey account more than my mastodon account, I hope this will be possible with flare.

**Comment by Tlaster** [comment]
Thank you for your kind words about Flare! I'm glad you're enjoying the app.

Regarding Sharkey support: Flare currently uses nodeinfo to detect the server type, and Sharkey isn't in Flare's detection list yet. However, since Sharkey is indeed a fork of Misskey, adding support for it should be relatively straightforward. I'll make sure to include Sharkey support in the next release.

Thanks for bringing this to my attention!
